version: '3.8'

services:
  app:
    build: .
    container_name: movie_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: movie_user
      DB_PASSWORD: your_strong_password
      DB_NAME: movie_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: movie_database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: movie_db
      MYSQL_USER: movie_user
      MYSQL_PASSWORD: your_strong_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db_data:
