### get all movies
GET http://localhost:3000/movies

### get movie by id
GET http://localhost:3000/movies/4

### get movie by criteries
POST http://localhost:3000/movies/search
Content-Type: application/json

{
    "title":"",
    "year":"",
    "rating":1,
    "actor":"",
    "genre":""

}

### get all genre
GET http://localhost:3000/movies/genres


### get all movies by genre
GET http://localhost:3000/movies/genres/2

### get all actors
GET http://localhost:3000/movies/actors

### get movies by actor
GET http://localhost:3000/movies/actors/2
