
### register user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "test223@test.com",
    "password": "test"
}

### list users
GET http://localhost:3000/api/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Niwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU0MzEwNzMxLCJleHAiOjE3NTQzMTQzMzF9.bIm2o1-zIu6wBtREIY2i_kGqt-INWBi397oEpMhhqbI

### login user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "test223@test.com",
    "password": "test"
}
### login admin
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password"
}

### test jwt
GET http://localhost:3000/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU0MzMxMjUzLCJleHAiOjE3NTQzMzQ4NTN9.m-oRIt-6tx0RZPvEsxTyBE3jrX4rqKdiMjzZKM2VgKI
#a token minden login után más

### update token
PUT http://localhost:3000/api/auth/refresh-token
refresh_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU0MzMxMzkyLCJleHAiOjE3NTQ5MzYxOTJ9.qRI1QFhUOTmhSyAYrocSCmZoirBAujgWiGv6vENHX70

### approve user
PATCH http://localhost:3000/api/auth/approval
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU0MzEwMDkwLCJleHAiOjE3NTQzMTM2OTB9.2L9nf6TSdajohhBxgmVDCAkSOMbdTZzxkDnwLQFbvi4
Content-Type: application/json

{
    "id": 2
}


### promote user
PATCH http://localhost:3000/api/auth/promotion
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU0MjEyOTI5LCJleHAiOjE3NTQyMTY1Mjl9.TlKAir6sLB2AoEIeA6lfuPbqctYoN3f7wSRih2hSnks
Content-Type: application/json

{
    "id": 2
}
